version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: dependabot
  ignore:
  - dependency-name: "@nestjs/testing"
    versions:
    - ">= 7.a, < 8"
